Get open ride endpoint
jaya-academy/ridely_node pull request #14
Opened 2024-05-05 12:17 UTC by tatsumibruno

Endpoint para ser utilizado pelo motorista, seria o "ping" procurando por uma corrida em aberto (aguardando o aceite)

2024-05-05 14:16 UTC, cazuzaneto requested changes
@tatsumibruno, esse novo endpoint ficará com o seguinte design: `/rides?driverId=123`, mas lá na doc, e no projeto de `kotlin `ele está assim: `/drivers/{id}/get-rides`. A sua implementação feita aqui neste pr me parece mais semântica. Posso alterar a doc e o projeto de kotlin para prevalecer essa?

2024-05-06 11:59 UTC, cazuzaneto commented on src/ride/ride.module.ts
> +  controllers: [RideController, DriverController],
@tatsumibruno, por que há a necessidade de declarar o DriverController aqui no módulo de Ride?

2024-05-06 12:02 UTC, tatsumibruno commented on src/ride/ride.module.ts
> +  controllers: [RideController, DriverController],
O endpoint somente é exposto se estiver declarado em um módulo.
Aí como estou entendendo que o Driver é uma entidade do contexto de Ride, coloquei aqui.
Faz sentido?

2024-05-06 12:06 UTC, cazuzaneto commented on src/ride/ride.module.ts
> +  controllers: [RideController, DriverController],
É que hoje ele já está exposto, pois em AppModule já há a importação de DriverModule.

2024-05-06 12:21 UTC, cazuzaneto approved these changes

2024-05-06 12:41 UTC, bruno-tatsumi-syngenta commented on src/ride/ride.module.ts
> +  controllers: [RideController, DriverController],
Ahhh eu não tinha me ligado que ja tinha o Driver module haha
Vou mover pra lá

2024-05-06 12:44 UTC, bruno-tatsumi-syngenta commented on src/ride/ride.module.ts
> +  controllers: [RideController, DriverController],
Feito, valeu @cazuzaneto

2024-05-06 12:47 UTC, tatsumibruno commented on src/ride/ride.module.ts
> +  controllers: [RideController, DriverController],
Não tinha reparado que já tinha um DriverController, arrumei agora
Valeu @cazuzaneto !

2024-05-06 12:56 UTC, cazuzaneto commented on src/ride/ride.module.ts
> +  controllers: [RideController, DriverController],
show man, pode mergear

2024-05-07 20:15 UTC, merged